name: clarity
recipe: drupal8
config:
  php: '7.2'
  via: apache:2.4
  webroot: web/
  database: mysql:5.7
  drush: '^10'
services:
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
  mailhog:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver
  claritydb:
    type: mysql
    creds:
      user: clarity
      password: clarity
      database: clarity
#  solr:
#    type: solr:7
#    portforward: false
#    core: lando
#    config:
#      dir: sites/all/modules/search_api_solr/solr-conf/7.x
tooling:
  vim:
    service: appserver
  sync-dev:
    service: appserver
    description: sync with Dev environment (need to connect to db)
    cmd:
      - composer install --prefer-dist
      - drush uli
  update-local:
    service: appserver
    description: sync all local config
    cmd:
      - drush cim -y
      - drush cim -y
      - drush cr
      - drush uli
  drush:
    cmd: /app/vendor/bin/drush
