services:
  config_ignore.event_subscriber:
    class: Drupal\config_ignore\EventSubscriber\ConfigIgnoreEventSubscriber
    arguments: ['@config.factory', '@module_handler']
    tags:
      - { name: event_subscriber }
