name: Config Ignore
type: module
description: Ignore certain configuration during imports and exports
core_version_requirement: ^8.8
package: Config
configure: config_ignore.settings

# Information added by Drupal.org packaging script on 2019-12-16
version: '8.x-2.2'
project: 'config_ignore'
datestamp: 1576528389
